const canvas = document.getElementById("bgCanvas");
const ctx = canvas.getContext("2d");

canvas.width = window.innerWidth;
canvas.height = window.innerHeight;

let particles = [];
const mouse = { x: null, y: null, radius: 150 };

window.addEventListener('mousemove', (e) => {
    mouse.x = e.x;
    mouse.y = e.y;
});

class Particle {
    constructor() {
        this.x = Math.random() * canvas.width;
        this.y = Math.random() * canvas.height;
        this.size = Math.random() * 2 + 1;
        this.speedX = Math.random() * 1 - 0.5;
        this.speedY = Math.random() * 1 - 0.5;
    }

    update() {
        this.x += this.speedX;
        this.y += this.speedY;

        if (this.x > canvas.width) this.x = 0;
        else if (this.x < 0) this.x = canvas.width;
        if (this.y > canvas.height) this.y = 0;
        else if (this.y < 0) this.y = canvas.height;
    }

    draw() {
       ctx.fillStyle = 'rgba(0, 255, 136, 0.8)';
        ctx.beginPath();
        ctx.arc(this.x, this.y, this.size, 0, Math.PI * 2);
        ctx.fill();
    }
}

function init() {
    particles = [];
    for (let i = 0; i < 100; i++) {
        particles.push(new Particle());
    }
}

function connect() {
    for (let a = 0; a < particles.length; a++) {
        for (let b = a; b < particles.length; b++) {
            let dx = particles[a].x - particles[b].x;
            let dy = particles[a].y - particles[b].y;
            let distance = Math.sqrt(dx * dx + dy * dy);

            if (distance < 150) {
                ctx.strokeStyle = `rgba(24, 119, 242, ${1 - distance/150})`;
                ctx.lineWidth = 1;
                ctx.beginPath();
                ctx.moveTo(particles[a].x, particles[a].y);
                ctx.lineTo(particles[b].x, particles[b].y);
                ctx.stroke();
            }
        }
    }
}

function animate() {
    ctx.clearRect(0, 0, canvas.width, canvas.height);
    particles.forEach(p => {
        p.update();
        p.draw();
    });
    connect();
    requestAnimationFrame(animate);
}

init();
animate();

window.addEventListener('resize', () => {
    canvas.width = window.innerWidth;
    canvas.height = window.innerHeight;
    init();
});
<script>
document.getElementById("downloadPdfBtn").addEventListener("click", () => {
    // Create a new PDF
    const { jsPDF } = window.jspdf;
    const doc = new jsPDF();

    // Example: Add some text content
    const gdp = document.getElementById('gdp_growth').value || "N/A";
    const vix = document.getElementById('vix_index').value || "N/A";
    const credit = document.getElementById('credit_spread').value || "N/A";
    const leverage = document.getElementById('leverage_ratio').value || "N/A";

    doc.setFontSize(18);
    doc.text("Financial Risk Report", 20, 20);

    doc.setFontSize(14);
    doc.text(`GDP Growth: ${gdp}%`, 20, 40);
    doc.text(`VIX Index: ${vix}`, 20, 50);
    doc.text(`Credit Spread: ${credit} bps`, 20, 60);
    doc.text(`Leverage Ratio: ${leverage}`, 20, 70);

    // Add more content if needed
    doc.text("Generated by NEXUS AI", 20, 90);

    // Save the PDF
    doc.save("Financial_Risk_Report.pdf");
});
</script>
